### ISSUE TITLE
Doesn't work properly for '%,.2f' on certain negative numbers

### ISSUE THREAD

**Issue by jinder** [madogiwa/format4js#4]
On certain negative numbers, the format string "%,.2f" results in a leading ,. It's not consistent, and doesn't happen with all negative numbers.  However, for -401798.08, the resulting string is "-,401,798.08" when it should be "-401,798.08".

**Comment by madogiwa** [comment]
Thank you for reporting the issue.
It seems that the issue caused by miss handling of sign character.
I will fix a bug.
